# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/audio.xdc

# IP: ip/audio_bram/audio_bram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_bram || ORIG_REF_NAME==audio_bram} -quiet] -quiet

# XDC: c:/Users/sarat/vivado_programs/Audio_jack/Audio_jack.gen/sources_1/ip/audio_bram/audio_bram_ooc.xdc
